[project]
name = "country-boundaries"
version = "0.1.0"
description = "Country boundaries by ISO Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "pyarrow>=21.0.0",
]
